### ISSUE TITLE
afterbuy xml api expects prices with coma as decimal separator

### ISSUE THREAD

**Issue by vanilla-thunder** [FATCHIP-GmbH/plugin-oxid5-oxid2afterbuy#7]
please have a look at sampe request from xml api documentation: here:
http://xmldoku.afterbuy.de/dokued/content.aspx?ctype=1&cid=54&pid=53&collapse=0

You need to change fcafterbuyapi.php in your private repository and add str_replace:
row 331: ````<SellingPrice>' . str_replace('.',',',$oArt->SellingPrice) . '</SellingPrice>````
row 340: ````<BuyingPrice>'.str_replace('.',',',$oArt->BuyingPrice).'</BuyingPrice>````

**Comment by FATCHIP-GmbH** [comment]
Thanks for the hint, please use support@fatchip.de for issue tracking in the future since we do not monitor the github issues. Thanks very much!

**Comment by andrefatchip** [comment]
Closing issue. Suggest is in code by PR.

**Comment by recompile** [comment]
This is also true for "ArtikelGewicht" in core/fco2aorder.php.

`$sOrderarticleParameters .= "&ArtikelGewicht_{$iSuffix}=" . str_replace(".", ",", $oOrderArticle->oxorderarticles__oxweight->value);`
